import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/internal/Observable';
import { SystemConfig } from '@app/config/system-config';

@Injectable({
  providedIn: 'root'
})
export class FinancialInstitutionService {

  constructor(
    private httpClient: HttpClient,
  ) { }

  getFinancialInstition(countryCode: string): Observable<any> {
    return this.httpClient.get(SystemConfig.apiBaseUrl + "/institutions-list/" + countryCode).pipe();
  }

  getSkuAutoGeneratedKey(): Observable<any> {
    return this.httpClient.get(SystemConfig.apiBaseUrl + "/get-last-fps-sku-id").pipe();
  }

  getFPSAutoGeneratedKey(): Observable<any> {
    return this.httpClient.get(SystemConfig.apiBaseUrl + "/get-last-fps-id").pipe();
  }  
}

export interface FinancialInstitution {
  id: number,
  title: string
}